---
title: "Basics"
metaTitle: "Welcome to Haptic Finance"
metaDescription: "Increase capital efficiency and reduce the impact of impermanent loss."
---

## What is Haptic?

The haptic protocol is a system of smart contracts designed to increase capital efficiency and to reduce the impact of impermanent loss. Stakers lock Haptic network token (HAP) as a collateral, enabling the issuance of tokenized debt (TDA). The pooled collateral model enables deep liquidity and eliminates the need for counterparts. Borrowers lock ETH to obtain a stablecoin denominated loan from a supported procotol and the funds are used to provide liquidity on a external automated market maker platform. The protocol tracks impermanent loss and provides compensation to honest borrowers along with the exchange fees generated by their liquidity. Stakers are rewarded for their role with staking rewards and yields generated by the Treasury. The system is built around composability principles and leverages existing protocols to achieve its functionality.

## Overview

Haptic is a dual token system, comprised of Haptic network token (HAP) and Tokenized Debt Asset (TDA). All TDA is backed by HAP tokens, with a collateralisation ratio (c-ratio) of 400%. Stakers incur in debt when they mint TDA, and they must pay it back before exiting the system. Stakers are incentivized to stake their HAP tokens in several ways. Firstly, if their account is in optimal health, they are entitled to a portion of the protocol's weekly inflationary supply. In addition, they will receive extra yields generated by the Treasury. Borrowers deposit ETH and obtain a stablecoin denominated loan, choosing from a supported protocol and a desired c-ratio. For example, they can obtain sUSD from Synthetix at 150%, or LUSD on Liquity at 120% c-ratio. Funds are used to add liquidity on the desired AMM platform (Uniswap at the moment). Borrowers earn from exchange fees generated by the liquidity, with additional impermanent loss protection disboursed in TDA. Lastly, they are incentivised to lock-in liquidity during high market volatility with unique NFT rewards. 


## Why use Haptic?

As explained above, there are two types of Haptic users, Borrowers and Stakers. The former use the platform to engage in liquidity provisioning and yield farming on selected pools, without having to sell their principal (ETH at the moment) and with added impermanent loss protection. The latter engage the protocol by staking HAP tokens and contributing to the debt pool depth, with the goal of earning from staking rewards and extra yields. 

## How does Haptic operate?

The protocol uses a decentralized governance structure, deeply inspired by other successful DeFi organizations. Precisely, we make use of a DAO, with various councils for different governance related tasks:
- Technical council, which controls the multisig for protocol upgrades. 
- Treasury council, which controls the Treasury multisig.
- Supervisor council, which oversees the DAO general operations.


## Links

[Website](https://haptic.finance) / [Medium](https://hapticfinance.medium.com/) / [Twitter](https://twitter.com/hapticfinance/) / [Discord](https://twitter.com/hapticfinance/) / [Github](https://github.com/hapticfinance/)